name: Checkov Docker IaC Scan

on:
  workflow_dispatch:

jobs:
  checkov_scan_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create output directory
        run: mkdir -p checkov_output

      - name: Run Checkov via Docker (text report)
        run: |
          docker run --rm -v ${{ github.workspace }}:/iac bridgecrew/checkov -d /iac -o cli \
            | tee checkov_output/results.txt || true

      - name: Run Checkov via Docker (JSON report)
        run: |
          docker run --rm -v ${{ github.workspace }}:/iac bridgecrew/checkov -d /iac -o json \
            > checkov_output/results.json || true

      - name: Upload Checkov Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: checkov-docker-results
          path: checkov_output
