name: Checkov IaC Scan

on:
  workflow_dispatch:

jobs:
  checkov_scan:
    name: Run Checkov Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Checkov
        run: |
          python -m pip install --upgrade pip
          pip install checkov

      - name: Run Checkov scan
        run: |
          mkdir -p checkov_output
          checkov -d . -o cli | tee checkov_output/results.txt || true
          checkov -d . -o json > checkov_output/results.json || true

      - name: Upload Checkov Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: checkov-results
          path: checkov_output
