name: Terrascan Scan

on:
 workflow_dispatch:

jobs:
  terrascan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run terrascan and save output
        run: |
          mkdir -p terrascan-output
          docker run --rm -v ${{ github.workspace }}:/iac tenable/terrascan scan -d /iac > terrascan-output/terrascan_report.txt

      - name: Upload terrascan report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: terrascan-report
          path: terrascan-output/terrascan_report.txt
 
