name: Trivy IaC Scan 
on:
  workflow_dispatch:

jobs:
  trivy-iac-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy Config Scan with Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/repo aquasec/trivy:latest config --format table -o /repo/trivy-iac-report.txt /repo

      - name: Upload Trivy Table Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-iac-table-report
          path: trivy-iac-report.txt
